# Let's calculate the total number of emails provided in the user's text input.

import csv


emails = """
110baked@gmail.com
123littlescholars@gmail.com
5022mgr@nationalvision.com
56westledge@gmail.com
aaron@sundtechnologies.com
aavery1@mtb.com
abel@ctabc.org
aburaimoh@restopros.co
acasinghino@wheelerclinic.org
acataldo@knft.com
aci@advancecommunications.com
aclark@summitwashholdings.com
acmecorp@acmemonaco.com
acorsetti@torringtonsavings.com
acruz@tunxis.edu
agapedesigns860@gmail.com
ajordan@rjmediagroup.com
akapetanopoulos@nbtbank.com
akshahantre13@gmail.com
al@evolvemyoffice.com
alctpost2@gmail.com
alexg@agcreativeworks.com
amanda@smalbino.com
amarshall@txcc.commnet.edu
americanlegionpost209ct@gmail.com
amroz@mtb.com
anderson.jimenez@robeks.net
andreolit@farmingtonseniors.org
angelosmarket349@gmail.com
anne.mcgaffigan@eversource.com
antoni.maljevic@gmail.com
anythingcustom72@gmail.com
april@familyrootsproducemarket.com
arobinson@renewalsne.com
art@senioradvocatect.com
ashlee@capturetheconcept.com
ashleigh@aem-accounting.com
ashley.zubeck@fox-pest.com
atterratoa@plainvilleschools.org
averzosa@stanleywhitman.org
batcheldera@plainvilleschools.org
bdeschaine@kbebuilding.com
begreat@bbgc.org
bellcitybarbershop@gmail.com
bencivengoko@gmail.com
bethelchamberct@gmail.com
bevelich@gmail.com
beverly@fairfieldctchamber.com
bgareau@titanhotelgroup.com
bhensley@capitalworkforce.org
bill@spargomachineproducts.com
billandsamsdiner1970@gmail.com
billpulsifer@pepsibristol.com
billymadore69@gmail.com
bistrotwenty4@gmail.com
bjoyce.thelearningcenter@gmail.com
bkpgbasics@gmail.com
blackwidowpestspecialists@gmail.com
blc.06013@gmail.com
blorek@fpsct.org
bob@barlowpump.com
bob@firehousediscountoil.com
bonniecerasale@gmail.com
borawskid@fpsct.org
bplfriends@burlingtonctlibrary.org
brian@bestwaymortgages.com
brian@mountsouthington.com
bridgetbarrieau@gmail.com
bristolhearingaids@gmail.com
bristolselfstorage1@gmail.com
brittany.bennett@exprealty.com
bryan@beesremodeling.com
bsams@havilandsams.com
buboutiqueclothingline@gmail.com
buckelectricllc@gmail.com
burlingtonvetcenter@gmail.com
bwalsh@farmingtonslr.com
calistroj@plainvilleschools.org
camppickleballct@gmail.com
carlo@psi-nesp.com
carmen@fasciaschocolates.com
carol.fitzgerald@newhorizonsvillage.com
carrie.wicks@gonetspeed.com
carriergroup@bycarrier.com
carthur@torringtonsavings.bank
casey.sheehey@aecom.com
cassandra.watson@edwardjones.com
ccanepa@kbwfinancial.com
ccostello@wolcottps.org
cdupont@spchs.com
cfsllc-info@cfsllc.com
cgorneault@reworldwaste.com
chamber@madisonct.com
chcguitarsllc@gmail.com
cheers@thebestwineshopintown.com
chip.servicemaster@gmail.com
chris.bafumo@cruiseplanners.com
chris.cccandy@gmail.com
chris@vanirinnovations.com
chriscasanova10@gmail.com
chrismooneylcsw@pm.me
christine.malay@hilton.com
christopher.frois@gmail.com
christopher.grosse@uconn.edu
churchoffice@uccplainville.org
cjasper@prudencecrandall.org
ckcount@gmail.com
ckoster@westfieldbank.com
clarecourter@completelybyclare.com
clayton@top-joes.com
clindstrom@thomastonsb.com
clinic1022@massageenvy.com
cmorgan@tunxiswealthmgmt.com
colleen.ververis@onedigital.com
communications@ctcommunitycare.org
contact@frostyhood.com
contact-us@ctfoodshare.org
contactus@ctspring.com
contactus@independenceunlimited.org
continuinged@fpsct.org
cortinatileplainville@gmail.com
courtney@freestylehr.com
cpodkowiak@primerica.com
cristina@undonesalonct.com
crycam@brookdale.com
csterling@ccsu.edu
csulvester@mtb.com
ct.norwalk.main@slcann.com
ctadvancedspine@gmail.com
curtcarlsonbuilderllc@gmail.com
czakowski@essex.financial
daiudi@imtlct.com
dajohnson@geico.com
dana@sparrowdas.com
daniel.poplawski1@t-mobile.com
danielsonstrom@bristolk12.org
daphne@robersontierney.com
daphne@techedproducts.com
darlene@hopepregnancycenterct.org
dave@element119.com
daveg@armoloyct.com
dawn@campcaninect.com
delorenzoj@plainvilleschools.org
design@accugrind.com
dgreco@websterbank.com
dhirx@hartfordathletic.com
dhopson@valuedtechnologyservices.com
diane.kozel@ndccorp.com
director@orangectchamber.com
divinehealth@gmail.com
dkcares@dkmovementcares.org
dkilbourne@kilbourneandtully.com
dkleinman@hinckleyallen.com
dkriscenski@cmhsgroup.com
donelle.daigle@ghymca.com
donna@kozakandsalina.com
doreen.stickney@imaginenation.org
drajadhilipkumar@healthtrax.net
droveto@thomastonsb.com
dryclean@edricks.com
drzervas@familyeyecaredr.com
dtedesco@ccompliancesolutions.com
dustydudewoodworks@gmail.com
dvanallen@websterbank.com
e.garces@cafereal.co
easthavenchamber01@gmail.com
easy@blbct.com
ecklerc@fpsct.org
ecunningham1@mtb.com
edward.benecchi@gmail.com
edwardb@ubifcu.com
efdeptula09@gmail.com
ekandrysawtz@motorleasecorp.com
elizabeth.dolan@insperity.com
email@harvestbakery.net
emily@riversideadvisor.com
enclavegrille@gmail.com
eric@ampmailbox.com
esheridan@ionbank.com
events@themobilepub.com
execdirector@darienctchamber.com
exitsupport@everydayrs.com
falconeb@plymouth.k12.ct.us
farmerstevel9@gmail.com
farmingtondsm@anthologyseniorliving.com
fbcf@fbcfct.org
finkc@fpsct.org
firstimpressionsalonllc@gmail.com
foodpantry@plymouthfoodpantry.org
fvstaff@homehelpershomecare.com
gary.curran@fullpowerradio.com
gary@gnhcc.com
gbrown@masonicare.org
gene@prentisscpa.com
genny.fonseca@nrwib.org
gffitnessbristol@gmail.com
ggorski@bngco.com
ghtavern511@gmail.com
gina@samsonmachine.com
ginvest264@gmail.com
greenwichchamber@greenwichchamber.com
greg@raver.ai
grer217@kellyservices.com
grindal-kellerk@region10ct.org
h4landscape@gmail.com
hamblerspizza@gmail.com
hamelinandsons@gmail.com
harris.may@coloniallifesales.com
hcc@hamdenchamber.com
heatherchirumbolo@bhhsne.com
hello@basecampwork.com
hello@creativejamartco.com
hello@dna.marketing
hello@farmingtonstorage.com
hello@optimistprojects.com
hello@smartflooringllc.com
hhormaza@fox61.com
highermedct@gmail.com
hollis.hartman@promedica.org
houseofbbqbacon@gmail.com
huberc@fpsct.org
hultsm@plymouth.k12.ct.us
huntingtonwoods@winnco.com
hyers@uchc.edu
hzimbouski@amci.com
ibitz@plainville-ct.gov
icecreaminbristol@gmail.com
inezstjames@gmail.com
info.massageandrecovery@gmail.com
info.thomaston@vivecollision.com
info@aeistaffing.com
info@allstarweddingpros.com
info@aquaturfclub.com
info@azconstructionllc.com
info@bankatpeoples.com
info@beekley.com
info@benbronzacademy.org
info@briansangels.org
info@bristolworksct.org
info@burlington-history.org
info@butchersandbakers.com
info@centralctchambers.org
info@chamberect.com
info@charteroakplumbing.com
info@chippanee.com
info@clarkdietrich.com
info@clinicaldynamics.com
info@connecticutheadshots.com
info@connstep.org
info@ctctool.com
info@ctwealthmgmt.com
info@cwresources.org
info@danburychamber.com
info@dumontagency.com
info@dynalock.com
info@eburnsmarketing.com
info@ffpct.org
info@fipconstruction.com
info@firstbristol.org
info@greatervalleychamber.com
info@heavenleemedspa.com
info@industrialriggers.com
info@interscape.com
info@kentct.com
info@kindcareusa.com
info@lakecompounce.com
info@lindquist-insurance.com
info@maidorganic.com
info@martincabinet.com
info@metal-finish.com
info@middlesexchamber.com
info@mysticchamber.org
info@ncccc.org
info@nectchamber.com
info@newenglandneedles.com
info@newimagephotoct.com
info@northeastproduce.com
info@nutmegsymphony.org
info@nwctchamberofcommerce.org
info@oldsaybrookchamber.com
info@omaspride.com
info@onebarnes.com
info@onespineatatime.net
info@petitfamilyfoundation.org
info@ridgefieldchamber.org
info@schoolstreetstudios.net
info@shadyoaksassistedliving.com
info@shepardmeadows.org
info@shorelinechamberct.com
info@simsburycoc.org
info@southingtonchamber.com
info@southwindsorchamber.org
info@spearbrostrees.com
info@stadiumxv.com
info@sullivan-brothers.com
info@terryvillelions.org
info@thebristolbazaar.com
info@thecarouselmuseum.org
info@thomasfitnessandperformance.com
info@tristatechamber.com
info@tunxisgolf.com
info@typsygypsyjewelry.com
info@ultimatewireforms.com
info@us.trumpf.com
info@valleyresidentialgroup.com
info@vetstronginc.org
info@wecarecomputers.com
info@westportwestonchamber.com
info@whchamber.com
info@wheelerclinic.org
info@wiltonchamber.com
info@windsorcc.org
info@wojtusiknurserycenter.com
insightplustom@gmail.com
irizarryn@fpsct.org
jackie@mizzyconstruction.com
jadelabella@bhhsne.com
jamaicankitchenct@gmail.com
james.ferris@lpl.com
jamesashner@gmail.com
janice.freschlin@dignitymemorial.com
japatel@websterbank.com
jason@famandfam.com
jaukstolis@hartfordminutemanpress.com
jay.sattler@claconnect.com
jbeale@thomastonsb.com
jcassidy@courant.com
jconcepcion@metrohartford.com
jcooper@spchs.com
jcrespo@precisehvachomeservices.com
jeff@borlarealestate.com
jengland@ahlgrenlandscaping.com
jesse@directadvantagemail.com
jessica.collins@hhchealth.org
jessica.dragan@insperity.com
jessica@crvchamber.org
jessicaw@morincorp.com
jglamour4u@gmail.com
jgonzalez@tmw-health.com
jim@advancedtreatmentsolutions.net
jimmy@luminariproductions.com
jkennedy@farmingtonlibraries.org
johnh@phoenixproductsco.com
kellyf@c4eh.org
kimh@hedcoinc.com
l.soucy@scorevolunteer.org
lauren.gentil@firstgroup.com
lawlor@palacetheaterct.org
lee.ulinskas@us.ebmpapst.com
lfcfarmington@gmail.com
lisa.roy@jax.org
marty@courseyfinancial.com
marylou.wadsworth@raveis.com
matt.baronowski@ptsmc.com
maureen@rosieslaundry.com
melissar@payhubpayments.com
metter@bristolarc.org
michellelevasseur@bristolk12.org
mmgorman@cmhacc.org
nathaniel_mardoc@comcast.com
pastor@stmkp.org
petalspixelsstudio@gmail.com
ponter@farmington-ct.org
president@bbandwe.org
pstrazzulla@buffalolodging.com
rathan@suseebiz.com
roziopainting@gmail.com
sales@plymouthspring.com
sarahl.bristolblues@gmail.com
sharon.l@aefcu.com
tccc@tollandcountychamber.org
tcgcandles2023@gmail.com
thewindowguyct@gmail.com
thomas.parker1@myaallc.com
thompson.d@burlingtonct.us
tshelansky@harperwhitfield.com
wes@jenksproductions.com
joe.dias@cbia.com
joe@citytruevalue.com
johedwsmi@gmail.com
john.p.ryan@cttech.org
john1334jf.ao@gmail.com
john@espotgamingcenter.com
john@hydroflow-northeast.com
john@jarosa.com
johnd@rowleyspring.com
johngrad@rstepmortgage.com
joseph.ercolano@uconn.edu
jpoudrier@gbact.com
jseagrave@barronfinancialgroup.com
julespoirier1955@gmail.com
juliam@prestigehg.com
juliastach14@gmail.com
junkbear2019@gmail.com
jusmanafort@manafort.com
jwedler@nutmegtv.com
kaitlyn@larsonsgardencenter.com
katecrow@crowleyauto.net
kbarwis@bristolhospital.org
kbrown@apple-rehab.com
kdube@nathealthcare.com
kelmore@deltadentalnj.com
kfinn@selectdentalmanagement.com
kglowa@kencore.com
kkrasicky@plymouthct.us
kmdera@loureiro.com
krista@hwgreenco.com
kristinabraham@bristolk12.org
kristinedeleo@bristolk12.org
ksb@adamssamartinocpa.com
ksmith@ct.wish.org
kstankus@bristolhospital.org
ktaylor@abhomecare.com
lastyles91@gmail.com
latanyafarrell@bristolk12.org
laura@bbubarter.com
laura@newcanaanchamber.com
lbhoffman@alz.org
lbudny@warnertheatre.org
leamccabe@bristolk12.org
lfercodini@fercodini.com
lholcomb@damicoconstruction.net
liberty@libertyrecycling.net
linda.iovanna@ccarc.com
lisa.morris@valentiwealthmanagement.com
lissa.jennings888@gmail.com
lizc@creativekitchensct.com
lleifert@conquestsolutions.com
lon@atrcompanies.com
lovelandk@plymouth.k12.ct.us
lward@waterburychamber.com
lyderk@region10ct.org
lynda@windowshopinc.com
lynette@stmc.com
marc.koss@gadonut.com
margie@webscapedesign.com
marilizfitzpatrick@bristolk12.org
marketing@womenshealthusa.com
mary@macmedicalusa.com
maryhawk@bristolk12.org
matt@tollmanspring.com
matthew.j.bub.t2hp@statefarm.com
maxpizza8@gmail.com
mayor@plymouthct.us
mbellino@iknowaguyfoodsllc.com
mearls@wolcottct.org
mesposito@chesprocott.org
mgrabowski@russellspeeders.com
michael.auletta@bauerct.com
michael.lung@elderly-care.com
michaelhiggins@bristolk12.org
mike.johndrow@americanpridelawncare.com
mike@falconpublicsafety.com
mikea.lrmconstruction@gmail.com
mikecaron@reps2resultsfitness.com
millie@manchesterchamber.com
mmartinez@uwwestcentralct.org
mmoses@milfordct.com
molender@mtb.com
monica.hedling@e-hps.com
monica.neighborhoodchimneys@gmail.com
mp@brassmillrx.com
mporto@rayjurgen.com
mprentiss@starshep.com
mrowe@bristolhousing.org
mschmelcke@ivesbank.com
msmith@ionbank.com
msposato@pepco-ft4.com
mst.mary@nationaldieco.com
mtdod3@gmail.com
mumsonmainllc@gmail.com
munchbox785@gmail.com
mvollono@t-vlaw.com
myra@mainstreamcanoe.com
mziogas@aahzs.com
naplesapizza@gmail.com
nataylor@charteroak.edu
netcohs@fpsct.org
nevermindshop@gmail.com
nicholas.rund.reyes@nikepolis.com
nicoleelliott@bhhsne.com
nicoler@cgicompany.com
nlebron@panelprofessionalsct.com
nmcc@newmilford-chamber.com
npelligrinelli@cwpm.net
nrophael@thedelamar.com
office@2020facilityservices.com
office@andrewsperryconstruction.com
office@bethelne.com
office@eurohomecare.net
office@greaternewbritainchamber.com
office@ptelectrical.com
office@qualitywireedm.com
office@wethersfieldchamber.com
officemanager@gothreeleaf.com
onofrio@brbc.org
pagliaccis333@gmail.com
paulhus@plainville-ct.gov
paulinaokon860@gmail.com
paulthepainterct@gmail.com
pawel@wearhouse.io
pciccone@bhhsne.com
pcooney@fureydonovan.com
pesposito@ctautomall.com
peterwininger@bristolk12.org
pj@csgct.com
plainville@baileycares.com
plainville@squarepegpizzeria.com
poolwaterpat@gmail.com
president@bristolhistoricalsociety.org
prestigeplumbingwerks@gmail.com
primopress@gmail.com
promo@slidersgrillbar.com
psheehan@cpe-electric.com
pswain@p-temp.com
punzo.iole@gmail.com
r.picard911@gmail.com
rbrowning@torringtonsavings.bank
rebeccaterricciano@gmail.com
receptionist@brookermemorial.org
reich@ironwoodcap.com
reikiwilltravel@gmail.com
rick@emilyscater.com
rickypiscottano@advancedwindowsystems.com
rlaquerre@laqcpa.com
rnellis@reachacademycharter.org
robertsa@plainvilleschools.org
roger@rdsmediallc.com
rose@dayonspring.com
rroth@littelfuse.com
rteske@culliganwaterco.com
ryanc@farmington-ct.org
sabreu@uchc.edu
salebr@johnboyleco.com
sales@aps-ct.com
sales@arrowmfg.com
sales@crescentmanufacturing.com
sales@diversitee123.com
sales@energyresourcesusa.net
sales@fourslide.com
sales@harjonmanufacturing.com
sales@itc1.net
sales@leespring.com
sales@patsiga.net
sales@precisionmethods.com
sales@radcliffwire.com
sales@rexforge.com
sarahlupa@bristolk12.org
saramckenzie1982@gmail.com
sbard@revolutionmortgage.com
sbraverman@randrbox.com
sbutwill@thomastonsb.com
scarletj424@gmail.com
schooloffice@stjosephbristol.org
scott@windingtrails.org
scottgaudet@bristolk12.org
sderoy@arborlodging.com
sdinneen@alexandertg.com
sdragovich@farmingtonpolo.com
sdubois@thomastonsb.com
servpro@team-luciani.com
sguay@mtb.com
shama@yellowkingbrews.com
shannon@barkerspecialty.com
shareena.echavarria@use.salvationarmy.org
sharon.pinette@holcim.com
shelly.bove@arthurgrussell.com
sheth@elcct.org
shirley.sullivan@bbrown.com
shopvividhuehome@gmail.com
shopwestfarms@taubman.com
simplyguitarstudio@gmail.com
sjoyce@capitalworkforce.org
slc-nb@keystonesenior.com
smarino@sandystv.com
smazzarella@salessearchpartners.com
smulcahy@bhwlawct.com
soothingways.co@gmail.com
specialolympicsct@soct.org
spencer@thenewcambridgeproject.com
sphelps@alliedinsurancectr.com
ssimpson@wolcottps.org
ssivetz@chrysaliscenterct.org
sslight@usamortgage.com
stamfordchamber@stamfordchamber.com
stapper@campcourant.org
stella@budsgoods.com
steve.damato@docpopcorn.com
steve@associatedct.com
steve@savinocpa.com
stevecbrc@gmail.com
stevefitz@power-fuels.com
steven.abbate@gmail.com
steven.f@restoration1.com
steven.sellati@comparioninsurance.com
sueercolani@bhhsne.com
suesellsct@gmail.com
suffridgea@plymouth.k12.ct.us
support@nvsnit.com
susan.marinelli@orafol.com
susan.salecky@cocc.com
susaneverett@bristolk12.org
swinbournea@hillstead.org
szafranj@fpsct.org
tanisha.baptiste@sba.gov
taylor@worldwidebev.com
tboswell@mottcorp.com
tdunn@wolcottct.org
tforward@mtb.com
tgiannini@finefettle.com
thecharmedoracle13@gmail.com
thehangryforkrestaurant@gmail.com
theodore.shafer@gmail.com
thom@nofluffagency.com
tim@galvinfinancialllc.com
tjfitzsimons@absne.com
tmadhen@ywcanewbritain.org
tmartin@modernmech.com
tom.martucci@labpins.com
tom@mazz.com
tom@usacontainerllc.com
tomassogroup@tbinb.com
tonnsorchard@gmail.com
travelingtcompany@gmail.com
treasurer@ccburlingtonct.org
twilson@cvmco.com
twmdevelopmentllc@gmail.com
unionville.ct@russellcellular.com
uphouse@csregroup.com
urbanstudiosct@gmail.com
usi-ap@idexcorp.com
uudoh@ionbank.com
vbookkeepingllc@gmail.com
veteransareheroesforever@gmail.com
vetmm421@gmail.com
vic@elmpress.com
vigliottid@plymouth.k12.ct.us
vincelambri@gmail.com
vmsmarketingllc@gmail.com
wadsworthr22@gmail.com
wallowitzj@plainvilleschools.org
wecare@funkfuneralhome.com
wecare@obrien-funeralhome.com
wecare@woodtickmemorial.com
wendy.a.palmisano@espn.com
westela@kkc-law.com
westendbristol@gmail.com
wg@zzglaw.com
wholenessacupuncturecenter@gmail.com
wiltsebrosgarage@gmail.com
withasplashmobile@gmail.com
wmascetti@acgna.com
wmicari@micarifinancial.com
wolcottnews@gmail.com
yetta@cheshirechamber.org
"""

email_list = [e.strip() for e in emails.splitlines() if e.strip()]
unique_emails = list(set(email_list))
duplicates_count = len(email_list) - len(unique_emails)

# Print counts
print(f"Total emails: {len(email_list)}")
print(f"Unique emails: {len(unique_emails)}")
print(f"Duplicate emails: {duplicates_count}")

# Save unique emails into a CSV file
with open("unique_emails.csv", "w", newline="") as csvfile:
    writer = csv.writer(csvfile)
    writer.writerow(["Email"])  # Header
    for email in sorted(unique_emails):  # Sort for readability
        writer.writerow([email])

print("✅ Unique emails saved to unique_emails.csv")